theme: jekyll-theme-minimal
title: RoBiMo-Trop Data processing and visualization
description: This website presents the data set gathered during the 3th measurement campaign in Amazonas region.
logo: https://github.com/SebastianZug/RoBiMo_Trop_DataSet/blob/main/html/robimo-trop.jpg?raw=true
